server:
  port: 8080
  #context-path: /girl

girl:
  cupSize: B
  age: 18
#content: "cupSize: ${cupSize}, age: ${age}"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  # mapper-locations: /edu/tinchiway/domain/mapper/*.xml #指定mapper.xml位置
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名
    default-fetch-size: 50 #结果集数量
    default-statement-timeout: 10 #超时
    auto-mapping-unknown-column-behavior: warning #指定发现自动映射目标未知列（或者未知属性类型）的行为



